brew "fish"
brew "git"
brew "hub"
brew "kakoune"
brew "node"
brew "postgresql"

tap "homebrew/cask-versions"

cask "adobe-creative-cloud"
cask "alfred3"
cask "amazon-photos"
cask "appcleaner"
cask "divvy"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "iina"
cask "jetbrains-toolbox"
cask "the-unarchiver"
cask "transmission"
