brew 'bat'
brew 'oven-sh/bun/bun'
brew 'eza'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'kakoune'
brew 'libpq'
brew 'postgresql@15'
brew 'ripgrep'

cask 'homebrew/cask-fonts/font-meslo-lg-nerd-font'
cask 'hyper'
cask 'iina'
cask 'logi-options+'
cask 'raycast'
cask 'spotify'
cask 'transmission'
cask 'webstorm'

mas 'AdGuard for Safari', id: 1440147259
mas 'Photomator', id: 1444636541
